modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/IAFEnvoy/TheRuler/issues"
license = "LGPL-3.0"

[[mods]]
modId = "the_ruler"
version = "${version}"
displayName = "The Ruler"
authors = "IAFEnvoy"
description = '''
Set force game rules for all worlds.
'''
logoFile = "logo.png"

[[dependencies.the_ruler]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.the_ruler]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.5)"
ordering = "NONE"
side = "BOTH"
