modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/IAFEnvoy/TheRuler/issues"
license = "LGPL-3.0"

[[mods]]
modId = "the_ruler"
version = "${version}"
displayName = "The Ruler"
authors = "IAFEnvoy"
description = '''
Set force game rules for all worlds.
'''
logoFile = "logo.png"

[[dependencies.the_ruler]]
modId = "neoforge"
type = "required"
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.the_ruler]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "the_ruler.mixins.json"
